### ISSUE TITLE
It could be ideal to add ACL for the uploads? :)

### ISSUE THREAD

**Issue by jeremyrajan** [badunk/multer-s3#20] opened 2016-03-27 13:52 UTC
It would be ideal, if the users are able to pass in ACL modes, during uploads :). Something like this:

```javascript
  var upload = that.s3.upload({
        Bucket: that.options.bucket,
        Key: filePath,
        ACL: 'public-read', <-- // (passed via main func)
        ContentType: contentType,
        Body: (_stream || file.stream)
      })
```

ref: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property

Something, we can pass it in a func. I can submit a pull request, with the change, if ok? 

Cheers,
Jeremy

**Comment by badunk** [comment] 2016-04-11 09:14
Duplicate of #11 

Thanks for the PR, I think @LinusU was working on passing the entire option through to aws-sdk

**Closed by badunk** 2016-04-11 09:14 UTC

**Comment by LinusU** [comment] 2016-04-11 09:28
Yes, in #16, it's mostly done, just need to address the comments. I might be able to fix it this weekend 👏

**Comment by jeremyrajan** [comment] 2016-04-12 09:04
great stuff thank you 👍
