### ISSUE TITLE
Publish 2.9.0 to npm

### ISSUE THREAD

**Issue by dconde7** [badunk/multer-s3#113] opened 2018-11-01 19:29 UTC
Latest package version available on npm is 2.7.0 - 2 years ago.
[https://www.npmjs.com/package/multer-s3](https://www.npmjs.com/package/multer-s3)

**Comment by LinusU** [comment] 2018-11-01 21:14
Dupe of #92, I'll contact Npm and see if they can help us out...

**Closed by LinusU** 2018-11-01 21:14 UTC
